In [ ]:
#We will look at different ways to create DataFrame 
#1)From Python Lists of Lists

In [11]:
import pandas as pd

In [2]:
data=[['kabir',99],['anshumaan',98],['aritra',77],['manan',88]]

In [3]:
data

[['kabir', 99], ['anshumaan', 98], ['aritra', 77], ['manan', 88]]

In [7]:
pd.DataFrame(data, columns=['Name','Marks'])

        Name  Marks
0      kabir     99
1  anshumaan     98
2     aritra     77
3      manan     88

In [ ]:
#2)From Dictionary of Lists

In [9]:
data={ "a":[4,6,3],"b":[44,56,55]}

In [10]:
data

{'a': [4, 6, 3], 'b': [44, 56, 55]}

In [11]:
df=pd.DataFrame(data)

In [12]:
print(df)

   a   b
0  4  44
1  6  56
2  3  55

In [ ]:
#3)From Numpy Array

In [13]:
import numpy as np

In [14]:
arr=np.array([[1,2],[3,4]])

In [17]:
df=pd.DataFrame(arr,columns=["A","B"])

In [18]:
df

   A  B
0  1  2
1  3  4

In [ ]:
#4)From EXCEL

In [24]:
df=pd.read_excel("data.xlsx.xlsx")

In [25]:
df

      Name  School  Marks
0  Shubham     SPS     34
1   Joshua     UPS     45
2     Jack     WPS     45
3     Alex     UIS     67
4  Jasmine     RTS     45
5    Rohan     RRY     88
6    Rishi  Luxury     77
7   Aakash     BBL     90

In [ ]:
# 5)From CSV Files
# df = pd.read_csv("data.csv")
# Use options like:
# sep, header, names, index_col, usecols, nrows, etc.
# Example:
# pd.read_csv("data.csv", usecols=["Name", "Age"])

In [ ]:
# 6)From JSON
# df = pd.read_json("data.json")

# Can also read from a URL or string.

In [10]:
#7) How to read from URL we will see

In [14]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
# print(df)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [17]:
#NOW WILL STUDY EDA(EXPLORATORY DATA ANALYSIS
# Exploratory Data Analysis (EDA) is an essential first step in any data science project.

# It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables. This process includes generating summary statistics, checking for missing or duplicate data, and creating visualizations like histograms, box plots, and scatter plots. The goal of EDA is to get a clear picture of what the data is telling you before applying any analysis or machine learning models.

# By exploring the data thoroughly, you can make better decisions about how to clean, transform, and model it effectively.


df.head() #Gives the first 5 rows

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
df.tail() #Gives the last 5 rows

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [19]:
df.info()   # Gives summary like total entries data type count etc.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [20]:
df.describe()  # mathematical things is told

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [22]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [23]:
df.shape

(244, 7)

In [16]:
# 8)From SQL Databases (Not Mostly used)
# import sqlite3
 
# conn = sqlite3.connect("mydb.sqlite")
# df = pd.read_sql("SELECT * FROM users", conn)